environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"

    - PYTHON: "C:\\Python27-x64"
      LMDB_IS_MASTER: "1"

    - PYTHON: "C:\\Python35-x64"
      LMDB_IS_MASTER: "1"

install:
  - "%PYTHON%\\python.exe -m pip install pytest ."

build: off

test_script:
  - "cd tests"
  - "%PYTHON%\\python.exe -m pytest ."
